# Main name
name: jenkins

services:
  # Service name
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: on-failure
    volumes:
      - jenkins_home:/var/jenkins_home

#Volumes
volumes:
  jenkins_home:
