# Main name
name: frontend-react
services:
  # Service name
  frontend-react:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend-react-image
    ports:
      - "8080:80"
    environment:
      TZ: "America/Sao_Paulo"